# The build part for Netlify with a Nuxt project
[build]
    base='/'
    publish='dist'
    command='nuxt generate'
    environment = { NODE_VERSION = "20.0.0" }

# We can put redirects 
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

